version: '3.4'

services:
  calbania-server:
    build:
      context: .
      dockerfile: ./Dockerfile
    network_mode: "host"
    depends_on:
      - redis
    restart: always
  redis:
    image: redis
    command: redis-server
    volumes:
      - /database:/database
    ports:
      - "6379:6379"
    restart: always